# Generated by Django 4.0 on 2021-12-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('major_id', models.IntegerField(max_length=10, primary_key='true', serialize=False)),
                ('major_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.IntegerField(max_length=10, primary_key='true', serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocphan.majors')),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('doc_id', models.IntegerField(max_length=10, primary_key='true', serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hocphan.subjects')),
            ],
        ),
    ]
