# Generated by Django 4.0 on 2021-12-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decent',
            fields=[
                ('decent_id', models.IntegerField(max_length=10, primary_key='true', serialize=False)),
                ('decent_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(max_length=10, primary_key='true', serialize=False)),
                ('user_mail', models.CharField(default='', max_length=50)),
                ('user_pass', models.CharField(default='', max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=10)),
                ('decent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.decent')),
            ],
        ),
    ]
