# Generated by Django 4.0 on 2021-12-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='decent_id',
            new_name='decent',
        ),
    ]
